apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iacaws.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                vpcCidrBlock:
                  type: string
                ec2InstanceType:
                  type: string
                ec2InstanceName:
                  type: string
                rdsInstanceType:
                  type: string
                rdsInstanceName:
                  type: string
                dbUsername:
                  type: string
                dbPassword:
                  type: string
  scope: Namespaced
  names:
    plural: iacaws
    singular: iacaws
    kind: IaCAWS
    shortNames:
      - iacaws
